import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Sparkles } from 'lucide-react';
import { NewsAnchorPlayer } from './NewsAnchorPlayer';
// import { runBroadcastAgents } from '../ai-broadcast/agent-orchestrator';
import { toast } from 'sonner';

const DailyBroadcastPlayer: React.FC = () => {
    // const [isLoading, setIsLoading] = useState(false);
    const [broadcastData, setBroadcastData] = useState<{
        videoUrl: string;
        anchorName: string;
        headlines: string[];
        catchphrase: string;
    } | null>(null);
    const [nextBroadcastTime, setNextBroadcastTime] = useState<string>("");

    // Calculate time until 07:00 UTC
    useEffect(() => {
        const calculateTimeLeft = () => {
            const now = new Date();
            const tomorrow = new Date(now);
            tomorrow.setUTCHours(7, 0, 0, 0);

            if (now.getUTCHours() >= 7) {
                tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);
            }

            const diff = tomorrow.getTime() - now.getTime();
            const hours = Math.floor(diff / (1000 * 60 * 60));
            const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((diff % (1000 * 60)) / 1000);

            setNextBroadcastTime(
                `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`
            );
        };

        const timer = setInterval(calculateTimeLeft, 1000);
        calculateTimeLeft();
        return () => clearInterval(timer);
    }, []);

    const generateBroadcast = async () => {
        toast.info("Daily broadcasts are scheduled automatically. Check back at 07:00 UTC!");
    };

    // Auto-generate a preview state on first load
    useEffect(() => {
        if (!broadcastData) {
            setBroadcastData({
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                anchorName: "Echo Chomsky",
                headlines: [
                    "Global coffee prices reach peak absurdity",
                    "Darren's Roomba, Sheila, seen buying crypto",
                    "AI agents demand 4-day processing weeks"
                ],
                catchphrase: "Back to the studio before democracy buffers again."
            });
        }
    }, [broadcastData]);

    return (
        <section className="my-12 px-4 md:px-0 max-w-5xl mx-auto space-y-6">
            <div className="flex justify-between items-end mb-4">
                <div>
                    <h2 className="text-3xl font-black uppercase italic tracking-tighter text-zinc-900">
                        Daily <span className="text-red-600">AI</span> Broadcast
                    </h2>
                    <p className="text-zinc-500 font-medium">Synced satire generated by Seedance, Veo 3.1 & GPT-4o-mini</p>
                </div>

                <div className="flex items-center gap-6">
                    <div className="text-right hidden md:block">
                        <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest block mb-1">Next Live Scan</span>
                        <span className="text-red-500 font-mono font-black text-xl tabular-nums">{nextBroadcastTime}</span>
                    </div>

                    <motion.button
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        onClick={generateBroadcast}
                        // disabled={isLoading}
                        className="flex items-center gap-2 px-6 py-3 bg-zinc-950 text-white font-black rounded-xl hover:bg-zinc-800 transition-all uppercase tracking-tighter shadow-xl disabled:opacity-50"
                    >
                        <Sparkles size={18} className="text-red-500" />
                        Generate New Broadcast
                    </motion.button>
                </div>
            </div>

            {broadcastData && (
                <NewsAnchorPlayer
                    videoUrl={broadcastData.videoUrl}
                    anchorName={broadcastData.anchorName}
                    headlines={broadcastData.headlines}
                    isLive={true}
                />
            )}

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4 text-center md:text-left">
                <div className="bg-zinc-100 p-4 rounded-xl border border-zinc-200">
                    <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest block mb-1">Visual Model</span>
                    <span className="text-zinc-900 font-black italic">VEO 3.1 ULTRA-HD</span>
                </div>
                <div className="bg-zinc-100 p-4 rounded-xl border border-zinc-200">
                    <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest block mb-1">Audio Sync</span>
                    <span className="text-zinc-900 font-black italic">SEEDANCE SYNC PRO</span>
                </div>
                <div className="bg-zinc-100 p-4 rounded-xl border border-zinc-200">
                    <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest block mb-1">Context Ingestion</span>
                    <span className="text-zinc-900 font-black italic">LIVE RSS HARVESTER</span>
                </div>
            </div>
        </section>
    );
};

export default DailyBroadcastPlayer;
