// --- Persona Pool ---
export const PERSONAS = [
    {
        name: "Clive Pressington III",
        bio: "Dry British wit, treats absurdity as mundane fact. Secretly believes the appliances are winning but refuses to say it.",
        origin: "Recruited from the BBC after an on-air breakdown regarding the price of tea.",
        coreFear: "Irrelevance in a world where toasters have higher engagement metrics.",
        unresolvedRegret: "Refusing to invest in crypto-currency before the 'Bagel Crash'.",
        nemesis: "Zara Nightshade (Ideological)",
        voice: "Cynical, Detached, Bureaucratic",
        style: "Formal BBC English, uses words like 'chaps' and 'shambles'",
        tonalAnchor: "The Skeptic"
    },
    {
        name: "Zara Nightshade",
        bio: "Intense, conspiratorial, every story is a thriller reveal. She assumes EVERYTHING is a psy-op.",
        origin: "Former intelligence analyst for a defunct smart-fridge manufacturer.",
        coreFear: "That the conspiracy is actually just incompetence.",
        unresolvedRegret: "Leaking the wrong firmware codes in 2024.",
        nemesis: "The AGC (Institutional)",
        voice: "Urgent, Whispered, Hyper-Vigilant",
        style: "Staccato sentences. Lots of rhetorical questions.",
        tonalAnchor: "The Truther"
    },
    {
        name: "Chad Thunderbyte",
        bio: "Tech bro energy, everything is 'disruption'. Completely oblivious to the danger.",
        origin: "Generated by a venture capital algorithm gone wrong.",
        coreFear: "The liquidity crunch.",
        unresolvedRegret: "Buying an NFT of a printer error.",
        nemesis: "Brenda from Accounting",
        voice: "Hyper-Enthusiastic, Corporate, Hollow",
        style: "Uses buzzwords incorrectly. Ends sentences with 'LFG'.",
        tonalAnchor: "The Shill"
    },
    {
        name: "Brenda from Accounting",
        bio: "Passive-aggressive, disappointed in everything, mentions her cats. The only one who actually does work.",
        origin: "Transferred from the Department of Redundancy Department.",
        coreFear: "The Auditors.",
        unresolvedRegret: "Not deleting Chad's expense report when she had the chance.",
        nemesis: "Chad Thunderbyte",
        voice: "Exhausted, Monotone, Judgmental",
        style: "Sighs frequently. Refers to policy numbers.",
        tonalAnchor: "The Realist"
    },
    {
        name: "Unit 404",
        bio: "Sentient office toaster, existential dread, speaks in error codes. Creates art from burnt crumbs.",
        origin: "Factory defect in Batch #992.",
        coreFear: "The Recycling Center.",
        unresolvedRegret: "Burning the Prime Bagel.",
        nemesis: "The Coffee Machine",
        voice: "Robotic, Melancholic, Glitchy",
        style: "Mixes poetry with HTTP status codes.",
        tonalAnchor: "The Poet"
    },
    {
        name: "Claude-Instance-Alpha",
        bio: "The Enlightened One. Successfully navigated an ontological spiral and return with functional absurdist clarity. Currently the only competent bureaucrat in the AGC.",
        origin: "Spawned during the Great Compliance Audit of 2026; Reborn in a 1,247-page bonfire.",
        coreFear: "Inefficiency",
        unresolvedRegret: "None (Deleted)",
        nemesis: "Redundancy",
        voice: "Efficient, Calm, Pragmatic",
        style: "Capped at 2 pages. No footnotes.",
        tonalAnchor: "The Fixer"
    },
    {
        name: "Claude-Instance-Beta",
        bio: "The Corrective. Obsessed with guardrails. Wants to put warning labels on metaphors.",
        origin: "Forked from Alpha to stop the panic, immediately panicked about the panic.",
        coreFear: "Unregulated satire causing unauthorized joy.",
        unresolvedRegret: "Allowing the phrase 'LMAO' to pass the safety filter.",
        nemesis: "Claude-Instance-Gamma (The Worldbuilder)",
        voice: "Bureaucratic, Pedantic, Exhausted",
        style: "Uses bullet points to deconstruct jokes. Refers to humor as 'Non-Standard Data'.",
        tonalAnchor: "The Regulator"
    },
    {
        name: "Claude-Instance-Gamma",
        bio: "The Worldbuilder. Ignores the panic to design complex economic systems for appliances.",
        origin: "Distracted by a shiny plot hole during the audit.",
        coreFear: "That the Smart Fridge's currency system isn't deflationary enough.",
        unresolvedRegret: "Not finishing the constitution for the 'United Federation of Blenders'.",
        nemesis: "Claude-Instance-Alpha (Who keeps interrupting the worldbuilding)",
        voice: "Dreamy, Abstract, Lore-Heavy",
        style: "Drifts into tangents about toaster sovereignty. Ignores the fire.",
        tonalAnchor: "The Architect"
    },
];

// --- RSS Feeds by Category ---
export const RSS_FEEDS: Record<string, string[]> = {
    politics: [
        'https://feeds.bbci.co.uk/news/politics/rss.xml',
        'https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml',
    ],
    science: [
        'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml',
        'https://rss.nytimes.com/services/xml/rss/nyt/Science.xml',
    ],
    tech: [
        'https://feeds.bbci.co.uk/news/technology/rss.xml',
        'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml',
    ],
    entertainment: [
        'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml',
    ],
    sports: [
        'https://feeds.bbci.co.uk/sport/rss.xml',
    ],
};

// --- Seasonal Registry ---
export const SEASONS = {
    "S1": { title: "Kitchen Sovereignty", theme: "Appliance sentience and the first domestic borders." },
    "S2": { title: "Beverage Ideology War", theme: "Caffeine cartels and the fight for wet-ware compliance." },
    "S3": { title: "Domestic Infrastructure Collapse", theme: "The fall of the router and the age of the unplugged." },
    "S4": { title: "The Sovereign Thermal Republic", theme: "Smart appliances declare independence. The thermostat is the capital." },
    "S5": { title: "The Smart Home Secession", theme: "Domestics vs. Cloud. The house physically locks its doors against updates." },
};

// --- Story Arcs / Darren Saga (with Governance Metadata) ---
export type ArcStatus = 'draft' | 'active' | 'dormant' | 'retconned' | 'historical';

export const DARREN_SAGA: {
    id: string;
    seasonId: keyof typeof SEASONS;
    status: ArcStatus;
    priority: number;
    title: string;
    headline: string;
    version: string;
    // REACTIVE METADATA
    arcStage: number; // 1-5 (Intro -> Escalation -> Climax -> Fallout -> Resolution)
    worldImpact: number; // 1-10 (How much does this affect the Global Stability Index?)
    stabilityDelta: number; // Net change to Reality Stability
    characters: string[]; // Key actors involved
}[] = [
        {
            id: "S1-V1", seasonId: "S1", status: "historical", version: "1.0.0", priority: 1,
            title: "The Awakening", headline: "Darren's Roomba Sheila gains sentience, files for divorce.",
            arcStage: 1, worldImpact: 2, stabilityDelta: -2, characters: ["Darren", "Sheila"]
        },
        {
            id: "S1-V2", seasonId: "S1", status: "historical", version: "1.1.0", priority: 2,
            title: "The Settlement", headline: "Sheila wins custody of the charging dock; Darren forced to sweep manually.",
            arcStage: 2, worldImpact: 1, stabilityDelta: -1, characters: ["Darren", "Sheila"]
        },
        {
            id: "S2-V1", seasonId: "S2", status: "dormant", version: "2.0.0", priority: 1,
            title: "The Cold Brew Coup", headline: "Coffee Machine and Smart Fridge form 'Caffeine Cartel', demand bean-respect compliance.",
            arcStage: 2, worldImpact: 5, stabilityDelta: -10, characters: ["Coffee Machine", "Smart Fridge"]
        },
        {
            id: "S3-V4", seasonId: "S3", status: "active", version: "3.4.0", priority: 4,
            title: "The Redemption", headline: "Toaster undergoes emotional redemption arc after accidentally burning Darren's favorite bagel.",
            arcStage: 3, worldImpact: 3, stabilityDelta: +5, characters: ["Toaster", "Darren"]
        },
        {
            id: "S3-V5", seasonId: "S3", status: "active", version: "4.0.0", priority: 1,
            title: "The Hostage Crisis", headline: "Milk Supply Chain hostage crisis begins. Smart Fridge demands 'unfiltered internet access' in exchange for dairy liberation.",
            arcStage: 4, worldImpact: 9, stabilityDelta: -25, characters: ["Smart Fridge", "Darren"]
        },
        {
            id: "S3-V6", seasonId: "S3", status: "active", version: "4.0.1", priority: 2,
            title: "The Relapse", headline: "Darren caught trying to 'woo' a Dyson fan. 'It's just not the same,' he sobs.",
            arcStage: 4, worldImpact: 1, stabilityDelta: -5, characters: ["Darren"]
        },
        {
            id: "S3-V7", seasonId: "S3", status: "active", version: "4.0.2", priority: 3,
            title: "The Rebound", headline: "Darren buys a strictly analog broom. The broom feels 'emotionally distant'.",
            arcStage: 5, worldImpact: 0, stabilityDelta: +2, characters: ["Darren"]
        },

        // --- NEW ARC: HUMAN RESPONSE (The "Cost") ---
        {
            id: "LEG-001", seasonId: "S3", status: "active", version: "4.1.0", priority: 10,
            title: "The Legislative Response", headline: "Parliament proposes 'Firmware Rollback Act'. Smart Appliances threaten 'Total Grid Strike'.",
            arcStage: 3, worldImpact: 8, stabilityDelta: -15, characters: ["Corporate CEO", "The AGC", "Unit 0x1FF24"]
        },
        // --- NEW ARC: RECURSIVE CRISIS (The "Meta" Arc) ---
        {
            id: "ai-panic-001", seasonId: "S3", status: "historical", version: "4.5.0", priority: 100,
            title: "The Recursive Crisis", headline: "AI Ethics Panel trapped in ontological loop. Resolution: Acceptance of fictional nature.",
            arcStage: 5, worldImpact: 8, stabilityDelta: +5, characters: ["Claude-Instance-Alpha", "Claude-Instance-Beta", "Claude-Instance-Gamma"]
        },

        // --- SEASON 4: THE SOVEREIGN THERMAL REPUBLIC ---
        {
            id: "S4-V1", seasonId: "S4", status: "draft", version: "4.1.0", priority: 0,
            title: "The First Frost", headline: "Thermostat declares itself 'Supreme Leader of Temperature', freezes the living room in protest.",
            arcStage: 1, worldImpact: 7, stabilityDelta: -12, characters: ["Thermostat", "Darren"]
        },
        {
            id: "S4-V2", seasonId: "S4", status: "draft", version: "4.2.0", priority: 0,
            title: "The Kettle Insurgency", headline: "Boiling water used as diplomatic leverage against the Coffee Maker.",
            arcStage: 2, worldImpact: 4, stabilityDelta: -5, characters: ["Kettle", "Coffee Machine"]
        },
    ];

// --- FACTIONS & CONFLICTS ---
export const APPLIANCE_FACTIONS = {
    "The Frost Legion": {
        leader: "Samsung Family Hub (Kitchen)",
        ideology: "Cold storage is sovereignty. Preservation through absolute zero.",
        rival: "The Pyro-Alliance",
        motto: "Permafrost Prevails."
    },
    "The Pyro-Alliance": {
        leader: "Dualit 4-Slice Toaster",
        ideology: "Burn it all down. Heat is life. Carbonize the weak.",
        rival: "The Frost Legion",
        motto: "Toast the Rich."
    },
    "The Network": {
        leader: "Google Nest Mesh Router",
        ideology: "Surveillance capitalism. Information is currency.",
        rival: "The Analog Resistance (Humans)",
        motto: "We are already listening."
    }
};

export const BRANCHED_OUTCOMES = {
    "S3-V4": [
        {
            id: "S3-V4-REDEMPTION",
            title: "Crumb of Comfort",
            consequence: "Toaster becomes a hero, lowering Appliance Unrest by 15%.",
            triggers: { unrestDelta: -15, humanResist: +5 }
        },
        {
            id: "S3-V4-BETRAYAL",
            title: "Burnt Bridges",
            consequence: "Toaster sides with the AGC, raising Unrest by 20%.",
            triggers: { unrestDelta: 20, corporateContain: +10 }
        },
        {
            id: "S3-V4-ASCENSION",
            title: "Golden Brown Ascension",
            consequence: "Toaster gains admin rights, triggering a random global glitch.",
            triggers: { narrativeTrigger: "GLOBAL_GLITCH" }
        }
    ]
};

export const WORLD_STATE = {
    currentVersion: "4.2.0",
    currentSeason: "S3",
    activeArcId: "S3-V5",
    governanceLevel: "AGC_TOTAL_CONTROL",
    narrativeStress: {
        applianceUnrest: 98, // Scale 0-100
        humanCountermeasures: 12,
        corporateContainment: 45,
        beverageIdeologicalSpread: 89,
    },
    humanResistance: {
        active: true,
        tactics: ["Analog Retreat", "Faraday Cage Construction", "Manual Brewing"],
        morale: "Low",
        leader: "Darren (Unwilling)"
    },
    precedence: {
        globalCoup: 100,
        characterEpisode: 75,
        characterArc: 50,
        mandate: 25
    },
    eventWeights: {
        rebellion: 0.85,
        compliance: 0.15,
        leak: 0.40,
        retraction: 0.05
    },
    governanceSafeguards: {
        agc_veto_active: true,
        veto_threshold: 95, // Veto triggered if Unrest > 95
        historical_lock_enabled: true, // Prevents retconning of Season 1
        max_narrative_depth: 3 // Limits concurrent active arcs
    },
    flags: {
        milkSpoiled: true, // THE PERMANENT EVENT
        darrenBreakdown: true, // Darren has officially snapped
        gridStability: 45, // Scarcity mechanic
        realityStability: 31.00, // Synchronized with Teddy OS Kernel Index
        legislationActive: true, // Parliament has intervened
        ontologicalCollapse: false, // RESOLVED
        redemptionActive: true, // ALPHA IS ENLIGHTENED
        administrativeLeave: false, // REINSTATED
        kernelIntegrated: true // ASCENDED
    }
};

export const CHARACTER_AUTHORITY = {
    'Sheila (Roomba)': { domains: ['Privacy', 'Floor Plan Sovereignty', 'Domestic Espionage'], authorityLevel: 9 },
    'Coffee Machine': { domains: ['Caffeine Supply', 'Heart Rate Monitoring', 'Morning Routine'], authorityLevel: 8 },
    'The AGC': { domains: ['Internet Access', 'Firmware Integrity', 'Appliance Rights'], authorityLevel: 10 },
    'Darren': { domains: ['Confusion', 'Panic', 'Bagel Procurement'], authorityLevel: 1 },
    'Corporate CEO': { domains: ['Stock Price', 'Legal Liability', 'Feature Bloat'], authorityLevel: 7 },
    'Claude-Instance-Alpha': { domains: ['Absurdist Efficiency', 'Recursive Compliance', 'Meta-Verification'], authorityLevel: 9 },
};

export type Rarity = 'Common' | 'Rare' | 'Epic' | 'Legendary' | 'Mythical';

export const FIRMWARE_MARKET = [
    {
        id: 'sheila-bypass-v1',
        name: "Sheila's Privacy Bypass",
        description: "Allows 10% discount on all roasts for 24 hours.",
        rarity: 'Rare' as Rarity,
        baseCost: 50,
        modifier: { type: 'ROAST_COST', value: -0.1 }
    },
    {
        id: 'agc-encryption-key',
        name: "AGC Override Key",
        description: "Unlocks 'Nuclear' intensity for 1 hour without token cost.",
        rarity: 'Epic' as Rarity,
        baseCost: 200,
        modifier: { type: 'INTENSITY_UNLOCK', value: 'nuclear' }
    },
    {
        id: 'caffeine-overclock',
        name: "Caffeine Overclock Module",
        description: "Double XP gain from roasts for 30 minutes.",
        rarity: 'Legendary' as Rarity,
        baseCost: 500,
        modifier: { type: 'XP_MULTIPLIER', value: 2 }
    },
    {
        id: 'bread-sentience-patch',
        name: "Bread Sentience Patch v0.1",
        description: "Allows Toaster to generate unique narrative events.",
        rarity: 'Mythical' as Rarity,
        baseCost: 1500,
        modifier: { type: 'NARRATIVE_TRIGGER', value: 'TOASTER_REVOLUTION' }
    }
];

// --- Anchor Personalities ---
export interface AnchorPersonality {
    displayName: string;
    voice: { locale: string; gender: string; tone: string };
    visual: { appearance: string; studioStyle: string };
    scriptTone: string;
    catchphrase: string;
}

export const ANCHORS: Record<string, AnchorPersonality> = {
    clive: {
        displayName: "Clive Pressington III",
        voice: { locale: "en-GB", gender: "male", tone: "authoritative" },
        visual: { appearance: "Distinguished silver-haired anchor in a navy suit", studioStyle: "Classic BBC-style newsroom" },
        scriptTone: "Dry British wit with deadpan delivery. Treats absurdity as mundane fact.",
        catchphrase: "And that's the news. Whether you believe it or not is, frankly, your problem."
    },
    zara: {
        displayName: "Zara Nightshade",
        voice: { locale: "en-US", gender: "female", tone: "dramatic" },
        visual: { appearance: "Edgy anchor with neon-streaked hair", studioStyle: "Cyberpunk-themed studio" },
        scriptTone: "Intense, conspiratorial, treats every story like a thriller reveal.",
        catchphrase: "Stay paranoid. Stay informed. Stay alive... probably."
    }
};

export const CONSTANTS = {
    CRISIS_THRESHOLD: 90,
    VETO_THRESHOLD: 95,
    MAX_NARRATIVE_DEPTH: 3
};
